name = "DynamicExpressions"
uuid = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
authors = ["MilesCranmer <miles.cranmer@gmail.com>"]
version = "0.15.0"

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StrideArrays = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
DynamicExpressionsLoopVectorizationExt = "LoopVectorization"
DynamicExpressionsSymbolicUtilsExt = "SymbolicUtils"
DynamicExpressionsZygoteExt = "Zygote"

[compat]
Aqua = "0.7"
Bumper = "0.6"
Compat = "3.37, 4"
Enzyme = "^0.11.12"
LoopVectorization = "0.12"
MacroTools = "0.4, 0.5"
PackageExtensionCompat = "1"
PrecompileTools = "1"
Reexport = "1"
StrideArrays = "0.1"
SymbolicUtils = "0.19, ^1.0.5"
Zygote = "0.6"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "SafeTestsets", "Aqua", "Enzyme", "ForwardDiff", "LoopVectorization", "SpecialFunctions", "StaticArrays", "SymbolicUtils", "Zygote"]
